### ISSUE TITLE
Question about broken build on ghost-tree due to Flake8 error

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#10]
And I broke the build tonight...but fixed it thanks to Travis.  My question is why did Flake8 not show an error locally for setup.py, but then when I pushed a commit Travis was *not* happy after checking the build (I had no reason whatsoever to mess with the setup.py file until it gave the error on Travis).  It doesn't look like there were any Flake8 updates... any thoughts?  I'm just curious...if you don't know, just ignore this.....  :scream:   @jairideout @ebolyen

![screen shot 2015-02-11 at 11 20 06 pm](https://cloud.githubusercontent.com/assets/7920357/6163287/d81fa012-b244-11e4-9f5e-e2cc56f380ec.png)

**Comment by ebolyen** [comment]
It looks like there was an update to the `pep8` package, which `flake8` runs. I was able to check that file without issue with pep8, but once I updated it, I got the same error message as above (on an older version of the file). Just run `pip install pep8 --upgrade` to patch your flake8.

**Comment by JTFouquier** [comment]
Ohhh I see.  That makes sense.  I'll update it tonight.  Thanks, Evan!

**Comment by JTFouquier** [comment]
Yes, that did the trick.  :ghost:  Thank you!
