### ISSUE TITLE
update to scikit-bio 0.2.3

### ISSUE THREAD

**Issue by jairideout** [JTFouquier/ghost-tree#11]
@JTFouquier scikit-bio 0.2.3 went live today, so I recommend updating to this latest version by running `pip install scikit-bio --upgrade`. `setup.py` also needs to be updated to depend on `scikit-bio >= 0.2.3`. This release included bug fixes related to #9. Please see the [release notes](https://github.com/biocore/scikit-bio/releases/tag/0.2.3) for more details and let me know if you have any issues with updating. Thanks!

**Comment by JTFouquier** [comment]
@jairideout Thanks! Update went well, and I fixed `setup.py`.
