### ISSUE TITLE
running ghost-tree tests leaves tmp directory behind

### ISSUE THREAD

**Issue by jairideout** [JTFouquier/ghost-tree#19]
When running ghost-tree's unit tests, a `tmp/` directory is created in the current working directory but is not cleaned up. The directory contains a single file (`mini_seq_gt.fasta`).

**Comment by jairideout** [comment]
Also, if the tests are then *rerun*, I get the following message:

```
$ nosetests
..mkdir: tmp: File exists
.....................
----------------------------------------------------------------------
Ran 23 tests in 0.866s

OK
```

**Comment by JTFouquier** [comment]
Thanks I'll look into this and the other issues. I'm really behind FYI.  Thank you!
