### ISSUE TITLE
add install instructions

### ISSUE THREAD

**Issue by jairideout** [JTFouquier/ghost-tree#20]
These should also note what external tools are required, their versions, website URL, and where/when they are required.

**Comment by JTFouquier** [comment]
This is drafted.  Where should this go?  Thanks!

**Comment by jairideout** [comment]
Awesome, thanks! I think README.rst is a good place for these instructions.

**Comment by JTFouquier** [comment]
Reopened.  I added instructions, but I'm going to try to add "checks" at the beginning of each script when they run the commands.

**Comment by JTFouquier** [comment]
@jairideout I learned about subprocess.Popen (based on @wasade suggestions) and love it!  That solved the issue with "muscle" and "fasttree" checks at the start of the script.  Gives a useful message if "command not found".  Always thought those were handy.  haha.
