### ISSUE TITLE
Allow phylogenetic tree as a foundation input instead of only foundation alignment .fasta

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#22]
Allow phylogenetic tree as a foundation input instead of only foundation alignment .fasta

Due to SILVA providing alignments, it was assumed that an alignment would be provided, but in some cases users might want to provide a .nwk tree as the foundation.

**Comment by gregcaporaso** [comment]
:+1: This will be a really important addition.

**Comment by JTFouquier** [comment]
Note to myself.  I bet skbio has a check for whether or not input is .nwk or .fasta....  just have user input one OR the other.... if .nwk pass, else _make_foundation_tree.  Should be super easy.

**Comment by JTFouquier** [comment]
@gregcaporaso, I realized that the way I have ghost-tree set up currently, it takes an **alignment file** and ghost-tree condenses this down to become "non redundant" **prior** to creating the foundation tree.  I am not sure how to address the issue of people giving me a tree that is not *non-redundant* because ghost-tree won't know where to graft the extensions.  i.e. if there are lots of places where *Candida* could go, what would it do? So I guess this will get readdressed another time. Does that sound accurate?  Thanks!

**Comment by JTFouquier** [comment]
addressed by: a8f522403d6ba41bb2560c188b71b5bd9246200c

**Comment by JTFouquier** [comment]
@gregcaporaso ghost-tree can (finally) accept a phylogenetic tree as a foundation 🎉
