### ISSUE TITLE
Location to host finished ghost-tree .nwk files for users to download

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#23]
Is there a more professional website for hosting the finalized .nwk ghost-tree files than google drive or drop box?  It would be easy for me to make a variety of the .nwk trees (combinations from different versions of UNITE/SILVA) and have them available.  For example, the UNITE DB for the .nwk I used was from a slightly older version of UNITE because that was what I used for analyzing my original ITS data a few years ago now.  

Thanks!

@jairideout and @gregcaporaso:

**Comment by gregcaporaso** [comment]
How big are the files? Best will probably be to include them in the github repo (e.g., in a top-level ``trees`` directory) - that way they are under revision control as well as the code. If they are too big, that might be an issue (though there are work-arounds).

**Comment by JTFouquier** [comment]
They are only ~1MB.  Looks like Github is okay with this size and the rest of the repository is small, so I'll store them here in a `trees` directory.  Thanks!
