### ISSUE TITLE
ghosttree.scaffold minor revision

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#29]
Suggestions from D.M. 
- should use os.mkdir
- use of globals is probably not necessary and adds complexity
- there are some blocks of code here which it isn't fully clear what is going on immediately.

**Comment by JTFouquier** [comment]
@wasade, I am using os.mkdir now and removed one of the global variables and checked the others.  One fails Pep8 unless I make it global, and the other makes ghost-tree fail completely.  I'm probably missing something on the global variables aspect...  Not a huge deal but if you see anything obvious let me know.  Thanks!

**Comment by wasade** [comment]
Okay, thanks. Surprising about the pep8 error... what was the specific one flagged?

**Comment by JTFouquier** [comment]
hybridtree.py:99:20: F821 undefined name 'foundation_accession_genus_dic'

**Comment by wasade** [comment]
Okay, that's indicating the variable doesn't exist so likely the
refactoring was incomplete. Removing the globals would be nice but I don't
think it is necessary
