### ISSUE TITLE
Travis is not running flake8 over scripts directory

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#34]
D.M. found issue: 
Travis is not running flake8 over the scripts directory. The ghost-tree script is not pep8 compliant.

**Comment by JTFouquier** [comment]
@wasade, @jairideout is this fixed now just by me adding ",py" to the ghost-tree script (so that flake8 can find it)?  I am not sure why we had ghost-tree script without a .py unless that was a typo. It now adheres to pep8. Thanks!

**Comment by jairideout** [comment]
@JTFouquier I have a pull request (#41) to fix this, please see the PR description for details.

**Comment by JTFouquier** [comment]
Hey @jairideout, when I ran flake8 over the ghost-tree directory, it used to be a lot easier to see the important files and the Pep8 requirements.  Now when I run flake8 I get tons of stuff, and it even freezes terminal.  It outputs DC_store, git/objects, etc.  So I have to specify one file at a time for flake8 to see.  Did I change something locally or should I add something to one of my config files?  Thank you!

**Comment by jairideout** [comment]
What command are you running? Can you post the output you get?

The travis-ci build is running the following command:

```
flake8 ghosttree setup.py scripts
```

**Comment by JTFouquier** [comment]
I used to run "flake8" over the folder I was working on, so something like "flake8 ghosttree/silva/"...  but it looks like I should be doing it similar to how travis is doing it, so I'll try that tonight. I can post some of the output but it literally won't stop running when I run flake8 over any folder now. Just keeps going and going and producing tons of flake8 errors.  But overall I think the travis way is the best!  thanks for the reminder.

**Comment by JTFouquier** [comment]
Hmmm, so I am really not sure what's going on here. When I run `flake8 ghosttree setup.py scripts`, I still get tons of the following, and I terminate it before it stops...  `alignmentoutput.txt` is just one of my files... shouldn't it not check `.txt` files?  Don't worry too much about it.  If Travis is happy, I can trouble shoot in my own time. Thanks @jairideout 

ghosttree/alignmentoutput.txt:99:66: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:77: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:77: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:92: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:92: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:108: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:108: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:121: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:121: E501 line too long (167 > 120 characters)
ghosttree/alignmentoutput.txt:99:121: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:135: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:135: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:99:144: E231 missing whitespace after ';'
ghosttree/alignmentoutput.txt:99:144: E702 multiple statements on one line (semicolon)
ghosttree/alignmentoutput.txt:100:121: E501 line too long (1618 > 120 characters)
ghosttree/extensions/.DS_Store:1:1: E901 TypeError: compile() expected string without null bytes
ghosttree/extensions/.DS_Store:1:121: E501 line too long (6148 > 120 characters)
ghosttree/extensions/.DS_Store:1:5177: W604 backticks are deprecated, use 'repr()'
ghosttree/extensions/.DS_Store:1:6149: W292 no newline at end of file

**Comment by jairideout** [comment]
@JTFouquier thanks for the details! I submitted a PR (#52) to resolve this.

**Comment by JTFouquier** [comment]
Awesome, @jairideout.  Oh, and for the most part I adhere to the 79 character line limit!  I added 120 really as a temporary fix.

**Comment by jairideout** [comment]
Sounds good!
