### ISSUE TITLE
graft unrooted extension trees as "rooted at midpoint"

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#35]
Extension trees are currently not rooted at midpoint before they get grafted onto the foundation tree.

From Greg:
 * Jennifier, do you root the extension trees? If not, that is probably something that we should add. Since we're using the tree for diversity calculations, I think midpoint rooting (TreeNode.root_at_midpoint) should suffice for this - you'd just need to add that before grafting. We could probably also get @johnchase to do this instead if you're too tied up with the new job - just let me know.

**Comment by JTFouquier** [comment]
@gregcaporaso : I added all of Daniel's suggestions to issue tracker and organized issues into two milestones: "BeforeSubmission" and "AfterSubmission".   If we move any other of Rob or Daniel's suggestions to higher priority I can address them before we redo PCoA and analyses.  I can try to address a lot of this soon.  Thanks!

**Comment by gregcaporaso** [comment]
@johnchase or @wasade, do you have some bandwidth to try this? It should be a really quick change.

**Comment by wasade** [comment]
Will issue a PR in an hour or so

**Comment by gregcaporaso** [comment]
Awesome, thank you!

**Comment by JTFouquier** [comment]
Thanks, I didn't realize that was that simple. I was a little overwhelmed with new issues last night.  One thing at a time.  Thanks!!  :)

**Comment by wasade** [comment]
No worries :)
