### ISSUE TITLE
add real and simulated OTU tables, along with the commands used for simulation

### ISSUE THREAD

**Issue by gregcaporaso** [JTFouquier/ghost-tree#38]
This will allow us to automate the analyses done in the paper, and will support some of the additional analyses that @rob-knight and @wasade suggested in our discussions with them. @JTFouquier, I can do the analyses if you can provide those files and the commands that you used for simulation and distance matrix creation.

**Comment by JTFouquier** [comment]
I emailed all this to you.  Includes original files, commands, simulated communities, new mapping, and PCoA outputs.  It was a pretty big folder.  Let me know if you'd like it here as well.  Thanks!

**Comment by JTFouquier** [comment]
Gosh, I'm so behind.  @gregcaporaso, this was for the "peer J pre print" right?  I can close this issue?  I'm updating things for the peer reviewed version... if we can still make it.  Thanks!

**Comment by gregcaporaso** [comment]
I think you should include the raw data and commands in the repository if
possible. How big is it? That will be useful as example data.

**Comment by JTFouquier** [comment]
Let me know if this is good @gregcaporaso.  Thx!  It was 8mb, so not bad.
