### ISSUE TITLE
Error while updating to the new SILVA and UNITE releases

### ISSUE THREAD

**Issue by vmikk** [JTFouquier/ghost-tree#75]
Dear Jennifer,
I tried to update ghost trees with the new SILVA and UNITE releases and have got an error at the last step (`scaffold hybrid-tree`):  `skbio.io._exception.UnrecognizedFormatError: Cannot read <emptyfile> into TreeNode, no reader found.` Could you please tell me what I'm doing wrong?

Here is the code I used:

```
# Download SILVA files (v.128, 2016-09-29)
wget 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.fasta.gz'
wget 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/taxonomy/tax_slv_ssu_128.acc_taxid'
wget 'https://www.arb-silva.de/fileadmin/silva_databases/release_128/Exports/taxonomy/tax_slv_ssu_128.txt'
gunzip -k SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.fasta.gz

# Download UNITE files (v7.1, 2016-08-22)
wget 'https://unite.ut.ee/sh_files/sh_qiime_release_s_22.08.2016.zip'
unzip sh_qiime_release_s_22.08.2016.zip

# Move unused files
mkdir unused/
mv QIIME_ITS_readme_22.08.2016.pdf sh_qiime_release_s_22.08.2016.zip \
  developer \
  SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.fasta.gz \
  ./unused/

## Variables
# Silva v128
silva_aligned='SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.fasta'
silva_accession='tax_slv_ssu_128.acc_taxid'
silva_taxonomy='tax_slv_ssu_128.txt'

# UNITE v.7
ITS_seqs='sh_refs_qiime_ver7_dynamic_s_22.08.2016.fasta'
ITS_tax='sh_taxonomy_qiime_ver7_dynamic_s_22.08.2016.txt'

# New file names
silva_fungi_only='silva_fungi_only.txt'
silva_fungi_filtered='silva_fungi_only_filtered.txt'
ITS_otu_map='ITS_otu_map.txt'
ghost_out="ghost-tree_OTU.nwk"

# Ghost-tree variables
GAP=0.9     # maximum gap frequency                                        
ENTROPY=0.8 # maximum position entropy
IDENT=0.8   # group the extension sequences at 80% identity


## Workflow
# Remove all non-fungal samples
ghost-tree silva extract-fungi "$silva_aligned" "$silva_accession" "$silva_taxonomy" "$silva_fungi_only"

# Filter entropy and gap positions
ghost-tree filter-alignment-positions "$silva_fungi_only" "$GAP" "$ENTROPY" "$silva_fungi_filtered"

# Group the extension sequences
ghost-tree extensions group-extensions "$ITS_seqs" "$IDENT" "$ITS_otu_map"

# Build the hybrid-tree
ghost-tree scaffold hybrid-tree "$ITS_otu_map" "$ITS_tax" "$ITS_seqs" "$silva_fungi_filtered" "$ghost_out"
```

I used
- ghost-tree 885b792 (Jun 21)
- scikit-bio v.0.2.3
- Python v.2.7.12
- FastTree v.2.1.9

Here is the input files for `ghost-tree scaffold hybrid-tree`: https://goo.gl/HaVi7P

With best regards,
Vladimir

**Comment by JTFouquier** [comment]
Thanks for reporting this and for the detailed report!  I've downloaded the files and I'm looking into it now.

**Comment by JTFouquier** [comment]
Hi Vladimir,

I ran ghost-tree with the files you sent, and it worked for me:
<img width="898" alt="screen shot 2016-10-12 at 6 57 09 pm" src="https://cloud.githubusercontent.com/assets/7920357/19333056/4aa2df7e-90af-11e6-8344-65875a845768.png">

One thing different I can see is that I am using FastTree 2.1.7 (here is the [change log](http://meta.microbesonline.org/fasttree/ChangeLog)) as it was updated after ghost-tree was originally developed. That might be the issue, but I'm not sure.  I'll add it to the issue tracker. If you find anything interesting, [please update the issue](https://github.com/JTFouquier/ghost-tree/issues/76). 

In the meantime, since I ran your files already, [here is your tree and the corresponding accession IDs](https://drive.google.com/open?id=0B8kQIWBnCII5UWdmMUlXM3lWYmM) in the tree. 

There are indeed going to be missing accession numbers as ghost-tree will always have trouble placing some tips on the tree. This is expected. From what we saw, it's still better to use ghost-tree as it provides phylogenetic insight, whereas the other metrics do not. 

Let me know if this helps!

Jennifer

**Comment by vmikk** [comment]
Hello Jennifer,
Thanks a lot for your answer and the tree.
I will try to use FastTree 2.1.7. Unfortunately, I could not find old binaries on the official website, so first I should compile it from the source.

With best regards,
Vladimir

**Comment by vmikk** [comment]
Hello Jennifer!
Unfortunately I still cannot succesfuly run `ghost-tree scaffold hybrid-tree`.
And this problem is not related to FastTree (I tried with 2.1.7 & 2.1.9 - all the same).

After running ghost-tree, it will succesfuly create `nr_foundation_alignment_gt.fasta` file (~ 1.9 MB).
Then it will start building a tree `nr_foundation_tree_gt.nwk` and will show an error:
```
Traceback (most recent call last):
  File "/home/mik/miniconda3/envs/GHOST/bin/ghost-tree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/mik/ghost-tree/scripts/ghost-tree", line 267, in <module>
    cli()
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mik/ghost-tree/scripts/ghost-tree", line 245, in hybrid_tree
    ghost_tree_output_folder)
  File "/home/mik/ghost-tree/ghosttree/scaffold/hybridtree.py", line 101, in extensions_onto_foundation
    std_error, ghost_tree_fp)
  File "/home/mik/ghost-tree/ghosttree/scaffold/hybridtree.py", line 232, in _make_foundation_tree
    foundation_tree = TreeNode.read(ghost_tree_fp + "/nr_foundation_tree_gt.nwk")
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/skbio/io/_registry.py", line 700, in read
    return skbio_io_read(fp, into=cls, format=format, **kwargs)
  File "/home/mik/miniconda3/envs/GHOST/lib/python2.7/site-packages/skbio/io/_registry.py", line 619, in read
    else 'generator'))
skbio.io._exception.UnrecognizedFormatError: Cannot read <emptyfile> into TreeNode, no reader found.
```

I tried with a fresh install of Ghost-tree on Ubuntu 16.04 LTS virtual machine:
```
## Install git
sudo apt install git
## Download FastTree
mkdir ~/bin/
cd ~/bin
wget http://www.microbesonline.org/fasttree/FastTree
chmod +x FastTree
cd ~
echo 'export PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
## Install Conda (http://conda.pydata.org/miniconda.html)
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
## Reoload terminal settings
source ~/.bashrc
## Create conda virtual environment and install ghost-tree
conda create --name GHOST -c biocore python=2 \
  scikit-bio=0.2.3 numpy cython pandas matplotlib jupyter click future
## Install Ghost-Tree
git clone https://github.com/JTFouquier/ghost-tree.git
source activate GHOST
cd ./ghost-tree/
pip install -e .

cd ~

ITS_otu_map='ITS_otu_map.txt'
ITS_tax='sh_taxonomy_qiime_ver7_99_s_20.11.2016.txt'     # UNITE v.7.1 (20.11.2016)
ITS_seqs='sh_refs_qiime_ver7_99_s_20.11.2016.fasta'
silva_fungi_filtered='silva_fungi_only_filtered.fasta'   # based on SILVA 128
ghost_out="TREE"                                         # new folder with ghost-tree results

ghost-tree scaffold hybrid-tree "$ITS_otu_map" "$ITS_tax" "$ITS_seqs" "$silva_fungi_filtered" "$ghost_out" --stderr
```
Input files are here: https://goo.gl/SldXSS

FastTree is working normally (e.g., `FastTree -nt silva_fungi_only_filtered.fasta > silva_tree.tree`)

**Comment by JTFouquier** [comment]
Hi @vmikk, thanks for the detailed report. I will get back to you soon about this!  -Jennifer

**Comment by JTFouquier** [comment]
Hi @vmikk, I am sorry, but I wasn't able to reproduce your error. I just recently made some more updates to ghost-tree (upgrade to **Python 3** and upgrade to **skbio 5.1**--skbio is the bioinformatics framework for ghost-tree). I did a fresh install and a new virtual environment and it is working for me. You can see the new files below. 

<img width="831" alt="screen shot 2016-11-28 at 3 05 07 pm" src="https://cloud.githubusercontent.com/assets/7920357/20688716/4297f0d6-b57f-11e6-899a-d635c06d7b43.png">

Let me know if this fixes your issue.  Thanks!!

**Comment by vmikk** [comment]
Hello Jennifer! Thanks for your reply!
I updated `ghost-tree` to the latest Python-3-based version and received the same error.
But then I noticed in README.rst that you use `fasttree` command (all letters are in lower case), renamed my `FastTree` (original spelling of the binary name from the author's site) and it works!
I am sorry for having bothered you.
I think we can close this issue.

**Comment by JTFouquier** [comment]
Oh no, well glad you got it to work. Thanks for letting me know. On [this line](https://github.com/JTFouquier/ghost-tree/blob/master/ghosttree/scaffold/hybridtree.py#L83) I added checks to make sure that fasttree is running, otherwise it should have given you an error. In my environment both "FastTree" and "fasttree" run the fasttree program. I'm a little confused. If you see an issue with this let me know. I'm not sure why you didn't receive an error. 

<img width="611" alt="screen shot 2016-11-30 at 10 01 20 am" src="https://cloud.githubusercontent.com/assets/7920357/20762564/01bce100-b6e4-11e6-8416-d9ab450d492c.png">
