### ISSUE TITLE
possible issue with newer versions of FastTree (2.1.8 & 2.1.9)

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#76]
We developed ghost-tree using 2.1.7 and it was updated later as shown in the [change log.](http://meta.microbesonline.org/fasttree/ChangeLog)... 

Figure out if these versions are not currently compatible with ghost-tree. If they are not compatible, update ghost-tree or indicate that there is a conflict. 

Related to issue #75

**Comment by vmikk** [comment]
This issue can be closed.
Ghos-tree works fine with the latest FastTree (v.2.1.9).

**Comment by JTFouquier** [comment]
Awesome, thank you!
